/* ============================================================
   Healthperia — i18n-doctorx.js
   Doctor index (dx.*) + doctor profile (dd.*) chrome, 9 langs.
   MERGE-style; loaded last on doctor-index.html / doctor-detail.html
   so it adds onto window.HP_I18N without clobbering earlier keys.
   ============================================================ */
window.HP_I18N = window.HP_I18N || {};
(function (I) {
  'use strict';
  function add(lang, obj) { I[lang] = Object.assign(I[lang] || {}, obj); }

  add('tr', { 'dx.country':'Ülke','dx.city':'Şehir','dx.specialty':'Branş','dx.name':'Doktor İsmi','dx.results':'doktor','dx.empty':'Eşleşen doktor bulunamadı.','dd.crumb':'Doktor','dd.notFound':'Doktor bulunamadı.','dd.back':'Doktor İndeksine dön','dd.cv':'Özgeçmiş','dd.academic':'Akademik Bilgi','dd.specialties':'Branşlar','dd.treatments':'Tedaviler','dd.contact':'İletişime Geç!','dd.listingsHead':'Healthperia Tedavileri' });
  add('en', { 'dx.country':'Country','dx.city':'City','dx.specialty':'Specialty','dx.name':'Doctor Name','dx.results':'doctors','dx.empty':'No matching doctor found.','dd.crumb':'Doctor','dd.notFound':'Doctor not found.','dd.back':'Back to Doctor Index','dd.cv':'Biography','dd.academic':'Academic Info','dd.specialties':'Specialties','dd.treatments':'Treatments','dd.contact':'Contact!','dd.listingsHead':'Healthperia Treatments' });
  add('de', { 'dx.country':'Land','dx.city':'Stadt','dx.specialty':'Fachgebiet','dx.name':'Arztname','dx.results':'Ärzte','dx.empty':'Kein passender Arzt gefunden.','dd.crumb':'Arzt','dd.notFound':'Arzt nicht gefunden.','dd.back':'Zurück zum Arztindex','dd.cv':'Biografie','dd.academic':'Akademische Info','dd.specialties':'Fachgebiete','dd.treatments':'Behandlungen','dd.contact':'Kontakt!','dd.listingsHead':'Healthperia Behandlungen' });
  add('ru', { 'dx.country':'Страна','dx.city':'Город','dx.specialty':'Специальность','dx.name':'Имя врача','dx.results':'врачей','dx.empty':'Подходящий врач не найден.','dd.crumb':'Врач','dd.notFound':'Врач не найден.','dd.back':'Назад к индексу врачей','dd.cv':'Биография','dd.academic':'Академическая информация','dd.specialties':'Специальности','dd.treatments':'Лечение','dd.contact':'Связаться!','dd.listingsHead':'Лечения Healthperia' });
  add('fr', { 'dx.country':'Pays','dx.city':'Ville','dx.specialty':'Spécialité','dx.name':'Nom du médecin','dx.results':'médecins','dx.empty':'Aucun médecin trouvé.','dd.crumb':'Médecin','dd.notFound':'Médecin introuvable.','dd.back':"Retour à l'index des médecins",'dd.cv':'Biographie','dd.academic':'Infos académiques','dd.specialties':'Spécialités','dd.treatments':'Traitements','dd.contact':'Contacter !','dd.listingsHead':'Traitements Healthperia' });
  add('es', { 'dx.country':'País','dx.city':'Ciudad','dx.specialty':'Especialidad','dx.name':'Nombre del médico','dx.results':'médicos','dx.empty':'No se encontró ningún médico.','dd.crumb':'Médico','dd.notFound':'Médico no encontrado.','dd.back':'Volver al índice de médicos','dd.cv':'Biografía','dd.academic':'Información académica','dd.specialties':'Especialidades','dd.treatments':'Tratamientos','dd.contact':'¡Contactar!','dd.listingsHead':'Tratamientos Healthperia' });
  add('pt', { 'dx.country':'País','dx.city':'Cidade','dx.specialty':'Especialidade','dx.name':'Nome do médico','dx.results':'médicos','dx.empty':'Nenhum médico encontrado.','dd.crumb':'Médico','dd.notFound':'Médico não encontrado.','dd.back':'Voltar ao índice de médicos','dd.cv':'Biografia','dd.academic':'Informações acadêmicas','dd.specialties':'Especialidades','dd.treatments':'Tratamentos','dd.contact':'Contatar!','dd.listingsHead':'Tratamentos Healthperia' });
  add('ar', { 'dx.country':'الدولة','dx.city':'المدينة','dx.specialty':'التخصص','dx.name':'اسم الطبيب','dx.results':'أطباء','dx.empty':'لم يتم العثور على طبيب مطابق.','dd.crumb':'طبيب','dd.notFound':'لم يتم العثور على الطبيب.','dd.back':'العودة إلى فهرس الأطباء','dd.cv':'السيرة الذاتية','dd.academic':'معلومات أكاديمية','dd.specialties':'التخصصات','dd.treatments':'العلاجات','dd.contact':'تواصل!','dd.listingsHead':'علاجات Healthperia' });
  add('nl', { 'dx.country':'Land','dx.city':'Stad','dx.specialty':'Specialisme','dx.name':'Naam arts','dx.results':'artsen','dx.empty':'Geen overeenkomende arts gevonden.','dd.crumb':'Arts','dd.notFound':'Arts niet gevonden.','dd.back':'Terug naar artsenindex','dd.cv':'Biografie','dd.academic':'Academische info','dd.specialties':'Specialismen','dd.treatments':'Behandelingen','dd.contact':'Contact!','dd.listingsHead':'Healthperia Behandelingen' });
})(window.HP_I18N);
