/* ============================================================
   Healthperia — Blog article (post) translations (HP_I18N)
   ============================================================ */
window.HP_I18N = window.HP_I18N || {};
(function (I) {
  I.tr = {
    'post.crumbCat':'Radyoloji',
    'post.title':'Tomografi 500 kat fazla radyasyon yayıyor!',
    'post.lead':'İngiltere\'de sağlıklı kişilerin vücut tomografisi çektirmesi yasaklandı. Sağlık Bakanlığı\'na göre, tomografi esnasında vücudun maruz kaldığı radyasyon, Hiroşima\'da atom bombasından kurtulan kişilerdeki kadar yüksek.',
    'post.intro':'İngiliz Sağlık Bakanlığı önceki akşam çok kritik bir karara imza atarak sağlıklı kişilerin vücut tomografisi çektirmesine yasak getirdi. Bu yasağa gidilmesine gerekçe olarak tomografi sırasında yayılan ve vücuda nüfuz eden radyasyon oranının çok yüksek olması gösterildi. Tomografi çektirmek geçen yıllarda osteoporoz, kalp rahatsızlığı, damar tıkanıklığı ve diyabet gibi hastalıkları önceden tespit edebildiği için sağlık uzmanları tarafından sıklıkla tavsiye ediliyordu.',
    'post.s1.h':'1 Tomografi 442 Röntgene Bedel','post.s1.p1':'Yayınlanan raporda sık tomografi çektirenlerin vücutlarındaki birikmiş radyasyon seviyesinin II. Dünya Savaşı\'nda Hiroşima ve Nagasaki\'ye atılan atom bombalarından kurtulanlarla eş seviyede olduğu belirtildi.','post.s1.p2':'Sıradan bir röntgen, vücudu görüntülemek için tek bir ışın gönderirken tomografide daha detaylı bir görüntü elde etmek için art arda birçok ışın gönderiliyor. 2009 sonunda California Üniversitesi\'nde görevli Prof. Rebecca Smith-Bindman\'ın 1119 kişiyi inceleyerek yürüttüğü araştırmada tek bir tomografinin 442 göğüs röntgenine ve 74 mamografiye (meme röntgeni) eş oranda radyasyon yaydığı ortaya çıkmıştı.',
    'post.s2.h':'Bilgisayarlı Tomografi (BT) Nedir?','post.s2.p1':'Bilgisayarlı tomografi, x-ışını (röntgen) kullanılarak vücudun incelenen bölgesinin kesitsel görüntüsünü oluşturmaya yönelik radyolojik teşhis yöntemidir. İnceleme sırasında hasta, bilgisayarlı tomografi cihazının masasında hareket etmeksizin yatar. Masa, manuel ya da uzaktan kumanda ile cihazın “gantry” adı verilen açıklığına sokulur.','post.s2.p2':'Cihaz bir bilgisayara bağlıdır. X-ışını kaynağı, incelenecek hasta etrafında 360 derecelik bir dönüş hareketi gerçekleştirirken “gantry” boyunca dizilmiş dedektörler tarafından x-ışını demetinin vücudu geçen kısmı saptanarak elde edilen veriler bir bilgisayar tarafından işlenir.',
    'post.s3.h':'MR\'ın yan etkisi yok!','post.s3.p1':'Uzmanlar tomografideki bu riske karşın MR\'ın hiçbir yan etkisi olmadığı konusunda görüş birliğine vardı. MR çekimleri sırasında sadece radyo dalgaları kullanılıyor; bunlar da insan sağlığına zararsız.','post.s3.p2':'Vücudun herhangi bir bölgesinin kesitsel olarak görüntülenmesidir. MR cihazı dev bir mıknatıstan oluşmaktadır. İnceleme sırasında hasta cihaz masasına yatırılmakta ve dev mıknatısın içinde bulunan tünele masa ilerletilmektedir. İnceleme sırasında mutlaka hareketsiz durmanız gerekmektedir.',
    'post.by':'Yazan:','post.role':'Moderatör','post.related':'İlgili Yazılar',
    'post.r1.cat':'Diş Sağlığı','post.r1.t':'Soğuk havalarda dişlerde neden ağrı oluşur?','post.r1.e':'Diş hassasiyeti ve soğuk hava arasındaki ilişkiyi inceledik.',
    'post.r2.cat':'Tedavi','post.r2.t':'Kullanılan tedaviler ne kadar doğru?','post.r2.e':'Kanıta dayalı tıp perspektifinden bir değerlendirme.',
    'post.r3.cat':'Sağlık Turizmi','post.r3.t':'Sağlık vizesine yeşil ışık','post.r3.e':'Sınır ötesi tedavi süreçleri için yeni uyum çerçevesi.'
  };
  I.en = {
    'post.crumbCat':'Radiology',
    'post.title':'CT scans emit 500 times more radiation!',
    'post.lead':'In the United Kingdom, body CT scans for healthy people have been banned. According to the Ministry of Health, the radiation the body is exposed to during a CT scan is as high as that of the survivors of the atomic bomb in Hiroshima.',
    'post.intro':'The previous evening, the British Ministry of Health made a very critical decision and banned body CT scans for healthy people. The reason given for this ban was that the level of radiation emitted during a CT scan and penetrating the body is very high. In previous years, CT scans were frequently recommended by health experts because they could detect diseases such as osteoporosis, heart conditions, vascular blockages and diabetes at an early stage.',
    'post.s1.h':'1 CT scan equals 442 X-rays','post.s1.p1':'The published report stated that the accumulated radiation level in the bodies of people who undergo frequent CT scans is on a par with that of the survivors of the atomic bombs dropped on Hiroshima and Nagasaki in World War II.','post.s1.p2':'While an ordinary X-ray sends a single beam to image the body, in a CT scan many beams are sent one after another to obtain a more detailed image. In a study conducted at the end of 2009 by Prof. Rebecca Smith-Bindman of the University of California, examining 1,119 people, it was revealed that a single CT scan emits as much radiation as 442 chest X-rays and 74 mammograms (breast X-rays).',
    'post.s2.h':'What is Computed Tomography (CT)?','post.s2.p1':'Computed tomography is a radiological diagnostic method that uses X-rays to create a cross-sectional image of the examined region of the body. During the examination, the patient lies on the table of the CT device without moving. The table is moved, manually or by remote control, into the opening of the device called the “gantry”.','post.s2.p2':'The device is connected to a computer. While the X-ray source performs a 360-degree rotational movement around the patient being examined, the portion of the X-ray beam passing through the body is detected by detectors arranged along the “gantry”, and the resulting data is processed by a computer.',
    'post.s3.h':'MRI has no side effects!','post.s3.p1':'Despite this risk in CT scans, experts reached a consensus that MRI has no side effects. Only radio waves are used during MRI scans; and these are harmless to human health.','post.s3.p2':'It is the cross-sectional imaging of any region of the body. The MRI device consists of a giant magnet. During the examination, the patient is laid on the device table and the table is advanced into the tunnel inside the giant magnet. During the examination you must remain completely still.',
    'post.by':'Written by:','post.role':'Moderator','post.related':'Related Articles',
    'post.r1.cat':'Dental Health','post.r1.t':'Why do teeth hurt in cold weather?','post.r1.e':'We examined the relationship between tooth sensitivity and cold weather.',
    'post.r2.cat':'Treatment','post.r2.t':'How correct are the treatments in use?','post.r2.e':'An evaluation from the perspective of evidence-based medicine.',
    'post.r3.cat':'Health Tourism','post.r3.t':'Green light for the health visa','post.r3.e':'A new compliance framework for cross-border treatment processes.'
  };
  I.de = {
    'post.crumbCat':'Radiologie',
    'post.title':'CT-Scans geben 500-mal mehr Strahlung ab!',
    'post.lead':'In Großbritannien wurden Körper-CT-Scans für gesunde Menschen verboten. Laut dem Gesundheitsministerium ist die Strahlung, der der Körper während eines CT-Scans ausgesetzt ist, so hoch wie bei den Überlebenden der Atombombe in Hiroshima.',
    'post.intro':'Das britische Gesundheitsministerium traf am Vorabend eine sehr kritische Entscheidung und verbot Körper-CT-Scans für gesunde Menschen. Als Begründung für dieses Verbot wurde angeführt, dass die während eines CT-Scans abgegebene und in den Körper eindringende Strahlung sehr hoch ist. In den vergangenen Jahren wurden CT-Scans von Gesundheitsexperten häufig empfohlen, da sie Krankheiten wie Osteoporose, Herzerkrankungen, Gefäßverschlüsse und Diabetes frühzeitig erkennen konnten.',
    'post.s1.h':'1 CT-Scan entspricht 442 Röntgenaufnahmen','post.s1.p1':'In dem veröffentlichten Bericht wurde festgestellt, dass der angesammelte Strahlungspegel im Körper von Menschen mit häufigen CT-Scans dem der Überlebenden der im Zweiten Weltkrieg auf Hiroshima und Nagasaki abgeworfenen Atombomben entspricht.','post.s1.p2':'Während eine gewöhnliche Röntgenaufnahme einen einzigen Strahl zur Abbildung des Körpers aussendet, werden bei einem CT-Scan viele Strahlen nacheinander gesendet, um ein detaillierteres Bild zu erhalten. In einer Ende 2009 von Prof. Rebecca Smith-Bindman an der University of California durchgeführten Studie mit 1.119 Personen zeigte sich, dass ein einziger CT-Scan so viel Strahlung abgibt wie 442 Brust-Röntgenaufnahmen und 74 Mammografien (Brust-Röntgen).',
    'post.s2.h':'Was ist Computertomografie (CT)?','post.s2.p1':'Die Computertomografie ist ein radiologisches Diagnoseverfahren, das mithilfe von Röntgenstrahlen ein Querschnittsbild der untersuchten Körperregion erstellt. Während der Untersuchung liegt der Patient bewegungslos auf dem Tisch des CT-Geräts. Der Tisch wird manuell oder per Fernbedienung in die als „Gantry“ bezeichnete Öffnung des Geräts geschoben.','post.s2.p2':'Das Gerät ist mit einem Computer verbunden. Während die Röntgenquelle eine 360-Grad-Drehbewegung um den zu untersuchenden Patienten ausführt, wird der durch den Körper hindurchtretende Teil des Röntgenstrahls von den entlang der „Gantry“ angeordneten Detektoren erfasst, und die gewonnenen Daten werden von einem Computer verarbeitet.',
    'post.s3.h':'Das MRT hat keine Nebenwirkungen!','post.s3.p1':'Trotz dieses Risikos beim CT erzielten die Experten einen Konsens, dass das MRT keine Nebenwirkungen hat. Bei MRT-Aufnahmen werden nur Radiowellen verwendet; und diese sind für die menschliche Gesundheit unbedenklich.','post.s3.p2':'Es handelt sich um die Querschnittsabbildung eines beliebigen Körperbereichs. Das MRT-Gerät besteht aus einem riesigen Magneten. Während der Untersuchung wird der Patient auf den Gerätetisch gelegt und der Tisch in den Tunnel innerhalb des riesigen Magneten geschoben. Während der Untersuchung müssen Sie unbedingt still liegen.',
    'post.by':'Geschrieben von:','post.role':'Moderator','post.related':'Ähnliche Artikel',
    'post.r1.cat':'Zahngesundheit','post.r1.t':'Warum schmerzen Zähne bei kaltem Wetter?','post.r1.e':'Wir haben den Zusammenhang zwischen Zahnempfindlichkeit und kaltem Wetter untersucht.',
    'post.r2.cat':'Behandlung','post.r2.t':'Wie richtig sind die angewandten Behandlungen?','post.r2.e':'Eine Bewertung aus der Perspektive der evidenzbasierten Medizin.',
    'post.r3.cat':'Gesundheitstourismus','post.r3.t':'Grünes Licht für das Gesundheitsvisum','post.r3.e':'Ein neuer Compliance-Rahmen für grenzüberschreitende Behandlungsprozesse.'
  };
  I.ru = {
    'post.crumbCat':'Радиология',
    'post.title':'КТ излучает в 500 раз больше радиации!',
    'post.lead':'В Великобритании запретили делать КТ всего тела здоровым людям. По данным Министерства здравоохранения, доза радиации, которую получает тело во время КТ, столь же высока, как у выживших после атомной бомбы в Хиросиме.',
    'post.intro':'Накануне вечером Министерство здравоохранения Великобритании приняло крайне важное решение и запретило делать КТ тела здоровым людям. Причиной запрета назвали очень высокий уровень радиации, излучаемой во время КТ и проникающей в тело. В прежние годы КТ часто рекомендовали специалисты, поскольку оно позволяло заранее выявлять такие заболевания, как остеопороз, болезни сердца, закупорка сосудов и диабет.',
    'post.s1.h':'1 КТ равно 442 рентгенам','post.s1.p1':'В опубликованном отчёте указано, что накопленный уровень радиации в теле людей, часто делающих КТ, находится на одном уровне с выжившими после атомных бомб, сброшенных на Хиросиму и Нагасаки во Второй мировой войне.','post.s1.p2':'Если обычный рентген отправляет один луч для получения изображения тела, то при КТ для получения более детального изображения один за другим отправляется множество лучей. В исследовании, проведённом в конце 2009 года профессором Калифорнийского университета Ребеккой Смит-Биндман с участием 1119 человек, выяснилось, что одно КТ излучает столько же радиации, сколько 442 рентгена грудной клетки и 74 маммографии (рентген груди).',
    'post.s2.h':'Что такое компьютерная томография (КТ)?','post.s2.p1':'Компьютерная томография — это радиологический метод диагностики, предназначенный для создания послойного изображения исследуемой области тела с помощью рентгеновских лучей. Во время исследования пациент неподвижно лежит на столе аппарата КТ. Стол вручную или с помощью пульта вводится в отверстие аппарата, называемое «гентри».','post.s2.p2':'Аппарат подключён к компьютеру. Пока источник рентгеновских лучей совершает вращательное движение на 360 градусов вокруг исследуемого пациента, часть рентгеновского пучка, проходящая через тело, регистрируется детекторами, расположенными вдоль «гентри», а полученные данные обрабатываются компьютером.',
    'post.s3.h':'У МРТ нет побочных эффектов!','post.s3.p1':'Несмотря на этот риск при КТ, специалисты пришли к единому мнению, что у МРТ нет никаких побочных эффектов. Во время МРТ используются только радиоволны; а они безвредны для здоровья человека.','post.s3.p2':'Это послойное изображение любой области тела. Аппарат МРТ состоит из огромного магнита. Во время исследования пациента укладывают на стол аппарата и продвигают стол в туннель внутри огромного магнита. Во время исследования необходимо оставаться полностью неподвижным.',
    'post.by':'Автор:','post.role':'Модератор','post.related':'Похожие статьи',
    'post.r1.cat':'Стоматология','post.r1.t':'Почему в холодную погоду болят зубы?','post.r1.e':'Мы изучили связь между чувствительностью зубов и холодной погодой.',
    'post.r2.cat':'Лечение','post.r2.t':'Насколько правильны применяемые методы лечения?','post.r2.e':'Оценка с точки зрения доказательной медицины.',
    'post.r3.cat':'Медицинский туризм','post.r3.t':'Зелёный свет медицинской визе','post.r3.e':'Новая нормативная база для трансграничного лечения.'
  };
  I.fr = {
    'post.crumbCat':'Radiologie',
    'post.title':'Le scanner émet 500 fois plus de radiations !',
    'post.lead':'Au Royaume-Uni, les scanners corporels pour les personnes en bonne santé ont été interdits. Selon le ministère de la Santé, les radiations auxquelles le corps est exposé pendant un scanner sont aussi élevées que celles des survivants de la bombe atomique d’Hiroshima.',
    'post.intro':'La veille au soir, le ministère britannique de la Santé a pris une décision très importante et a interdit les scanners corporels pour les personnes en bonne santé. La raison invoquée pour cette interdiction est que le taux de radiations émis pendant un scanner et pénétrant dans le corps est très élevé. Ces dernières années, les scanners étaient fréquemment recommandés par les experts de la santé car ils permettaient de détecter précocement des maladies telles que l’ostéoporose, les troubles cardiaques, les obstructions vasculaires et le diabète.',
    'post.s1.h':'1 scanner équivaut à 442 radiographies','post.s1.p1':'Le rapport publié indique que le niveau de radiations accumulé dans le corps des personnes qui passent souvent des scanners est comparable à celui des survivants des bombes atomiques larguées sur Hiroshima et Nagasaki pendant la Seconde Guerre mondiale.','post.s1.p2':'Alors qu’une radiographie ordinaire envoie un seul faisceau pour imager le corps, lors d’un scanner de nombreux faisceaux sont envoyés les uns après les autres pour obtenir une image plus détaillée. Dans une étude menée fin 2009 par la Prof. Rebecca Smith-Bindman de l’Université de Californie sur 1 119 personnes, il est apparu qu’un seul scanner émet autant de radiations que 442 radiographies du thorax et 74 mammographies (radiographies du sein).',
    'post.s2.h':'Qu’est-ce que la tomodensitométrie (scanner) ?','post.s2.p1':'La tomodensitométrie est une méthode de diagnostic radiologique visant à créer une image en coupe de la région examinée du corps à l’aide de rayons X. Pendant l’examen, le patient est allongé sans bouger sur la table de l’appareil. La table est introduite, manuellement ou par télécommande, dans l’ouverture de l’appareil appelée « gantry ».','post.s2.p2':'L’appareil est relié à un ordinateur. Pendant que la source de rayons X effectue un mouvement de rotation de 360 degrés autour du patient examiné, la partie du faisceau de rayons X traversant le corps est détectée par des détecteurs alignés le long du « gantry », et les données obtenues sont traitées par un ordinateur.',
    'post.s3.h':'L’IRM n’a pas d’effets secondaires !','post.s3.p1':'Malgré ce risque lié au scanner, les experts s’accordent à dire que l’IRM n’a aucun effet secondaire. Lors des examens IRM, seules des ondes radio sont utilisées ; et celles-ci sont sans danger pour la santé humaine.','post.s3.p2':'Il s’agit de l’imagerie en coupe de n’importe quelle région du corps. L’appareil d’IRM est constitué d’un aimant géant. Pendant l’examen, le patient est allongé sur la table de l’appareil et la table est avancée dans le tunnel situé à l’intérieur de l’aimant géant. Pendant l’examen, vous devez impérativement rester immobile.',
    'post.by':'Rédigé par :','post.role':'Modérateur','post.related':'Articles similaires',
    'post.r1.cat':'Santé dentaire','post.r1.t':'Pourquoi les dents font-elles mal par temps froid ?','post.r1.e':'Nous avons examiné le lien entre la sensibilité dentaire et le froid.',
    'post.r2.cat':'Traitement','post.r2.t':'Les traitements utilisés sont-ils corrects ?','post.r2.e':'Une évaluation sous l’angle de la médecine fondée sur les preuves.',
    'post.r3.cat':'Tourisme médical','post.r3.t':'Feu vert pour le visa de santé','post.r3.e':'Un nouveau cadre de conformité pour les soins transfrontaliers.'
  };
  I.es = {
    'post.crumbCat':'Radiología',
    'post.title':'¡La tomografía emite 500 veces más radiación!',
    'post.lead':'En el Reino Unido se ha prohibido a las personas sanas hacerse tomografías de cuerpo. Según el Ministerio de Sanidad, la radiación a la que se expone el cuerpo durante una tomografía es tan alta como la de los supervivientes de la bomba atómica de Hiroshima.',
    'post.intro':'La noche anterior, el Ministerio de Sanidad británico tomó una decisión muy importante y prohibió las tomografías de cuerpo a las personas sanas. Como motivo de esta prohibición se señaló que el nivel de radiación emitido durante la tomografía y que penetra en el cuerpo es muy alto. En años anteriores, las tomografías eran recomendadas con frecuencia por los expertos en salud porque permitían detectar de forma temprana enfermedades como la osteoporosis, las afecciones cardíacas, las obstrucciones vasculares y la diabetes.',
    'post.s1.h':'1 tomografía equivale a 442 radiografías','post.s1.p1':'El informe publicado indicó que el nivel de radiación acumulada en el cuerpo de las personas que se hacen tomografías con frecuencia está al mismo nivel que el de los supervivientes de las bombas atómicas lanzadas sobre Hiroshima y Nagasaki en la Segunda Guerra Mundial.','post.s1.p2':'Mientras que una radiografía corriente envía un solo haz para obtener una imagen del cuerpo, en la tomografía se envían muchos haces uno tras otro para obtener una imagen más detallada. En un estudio realizado a finales de 2009 por la Prof. Rebecca Smith-Bindman, de la Universidad de California, con 1119 personas, se reveló que una sola tomografía emite tanta radiación como 442 radiografías de tórax y 74 mamografías (radiografías de mama).',
    'post.s2.h':'¿Qué es la tomografía computarizada (TC)?','post.s2.p1':'La tomografía computarizada es un método de diagnóstico radiológico destinado a crear una imagen en corte de la región examinada del cuerpo mediante rayos X. Durante el examen, el paciente permanece tumbado sin moverse en la mesa del equipo de TC. La mesa se introduce, de forma manual o por control remoto, en la abertura del equipo denominada «gantry».','post.s2.p2':'El equipo está conectado a un ordenador. Mientras la fuente de rayos X realiza un movimiento de rotación de 360 grados alrededor del paciente examinado, la parte del haz de rayos X que atraviesa el cuerpo es detectada por los detectores dispuestos a lo largo del «gantry», y los datos obtenidos son procesados por un ordenador.',
    'post.s3.h':'¡La resonancia no tiene efectos secundarios!','post.s3.p1':'A pesar de este riesgo de la tomografía, los expertos llegaron al consenso de que la resonancia magnética no tiene ningún efecto secundario. Durante las resonancias solo se utilizan ondas de radio; y estas son inofensivas para la salud humana.','post.s3.p2':'Es la obtención de imágenes en corte de cualquier región del cuerpo. El equipo de resonancia consta de un imán gigante. Durante el examen, el paciente se tumba en la mesa del equipo y la mesa se introduce en el túnel situado dentro del imán gigante. Durante el examen debe permanecer totalmente inmóvil.',
    'post.by':'Escrito por:','post.role':'Moderador','post.related':'Artículos relacionados',
    'post.r1.cat':'Salud dental','post.r1.t':'¿Por qué duelen los dientes con el frío?','post.r1.e':'Analizamos la relación entre la sensibilidad dental y el frío.',
    'post.r2.cat':'Tratamiento','post.r2.t':'¿Qué tan correctos son los tratamientos utilizados?','post.r2.e':'Una evaluación desde la perspectiva de la medicina basada en la evidencia.',
    'post.r3.cat':'Turismo médico','post.r3.t':'Luz verde para el visado sanitario','post.r3.e':'Un nuevo marco de cumplimiento para los tratamientos transfronterizos.'
  };
  I.pt = {
    'post.crumbCat':'Radiologia',
    'post.title':'A tomografia emite 500 vezes mais radiação!',
    'post.lead':'No Reino Unido, foi proibido às pessoas saudáveis fazerem tomografia ao corpo. Segundo o Ministério da Saúde, a radiação a que o corpo é exposto durante uma tomografia é tão elevada como a dos sobreviventes da bomba atómica de Hiroxima.',
    'post.intro':'Na noite anterior, o Ministério da Saúde britânico tomou uma decisão muito importante e proibiu as tomografias ao corpo para pessoas saudáveis. Como motivo para esta proibição, apontou-se que o nível de radiação emitido durante a tomografia e que penetra no corpo é muito elevado. Nos anos anteriores, as tomografias eram frequentemente recomendadas pelos especialistas de saúde porque permitiam detetar precocemente doenças como a osteoporose, problemas cardíacos, obstruções vasculares e diabetes.',
    'post.s1.h':'1 tomografia equivale a 442 radiografias','post.s1.p1':'O relatório publicado indicou que o nível de radiação acumulada no corpo das pessoas que fazem tomografias com frequência está ao mesmo nível do dos sobreviventes das bombas atómicas lançadas sobre Hiroxima e Nagasáqui na Segunda Guerra Mundial.','post.s1.p2':'Enquanto uma radiografia comum envia um único feixe para obter uma imagem do corpo, na tomografia são enviados muitos feixes uns a seguir aos outros para obter uma imagem mais detalhada. Num estudo realizado no final de 2009 pela Prof. Rebecca Smith-Bindman, da Universidade da Califórnia, com 1119 pessoas, verificou-se que uma única tomografia emite tanta radiação como 442 radiografias ao tórax e 74 mamografias (radiografias à mama).',
    'post.s2.h':'O que é a tomografia computorizada (TC)?','post.s2.p1':'A tomografia computorizada é um método de diagnóstico radiológico destinado a criar uma imagem em corte da região examinada do corpo utilizando raios X. Durante o exame, o paciente permanece deitado sem se mover na mesa do equipamento de TC. A mesa é introduzida, manualmente ou por controlo remoto, na abertura do equipamento designada por «gantry».','post.s2.p2':'O equipamento está ligado a um computador. Enquanto a fonte de raios X realiza um movimento de rotação de 360 graus em torno do paciente examinado, a parte do feixe de raios X que atravessa o corpo é detetada pelos detetores dispostos ao longo do «gantry», e os dados obtidos são processados por um computador.',
    'post.s3.h':'A ressonância não tem efeitos secundários!','post.s3.p1':'Apesar deste risco na tomografia, os especialistas chegaram a consenso de que a ressonância magnética não tem qualquer efeito secundário. Durante as ressonâncias são usadas apenas ondas de rádio; e estas são inofensivas para a saúde humana.','post.s3.p2':'É a obtenção de imagens em corte de qualquer região do corpo. O equipamento de ressonância é constituído por um íman gigante. Durante o exame, o paciente é deitado na mesa do equipamento e a mesa é introduzida no túnel situado dentro do íman gigante. Durante o exame, é imprescindível permanecer imóvel.',
    'post.by':'Escrito por:','post.role':'Moderador','post.related':'Artigos relacionados',
    'post.r1.cat':'Saúde dentária','post.r1.t':'Porque é que os dentes doem com o frio?','post.r1.e':'Analisámos a relação entre a sensibilidade dentária e o frio.',
    'post.r2.cat':'Tratamento','post.r2.t':'Quão corretos são os tratamentos utilizados?','post.r2.e':'Uma avaliação na perspetiva da medicina baseada em evidências.',
    'post.r3.cat':'Turismo de saúde','post.r3.t':'Luz verde para o visto de saúde','post.r3.e':'Um novo quadro de conformidade para os tratamentos transfronteiriços.'
  };
  I.ar = {
    'post.crumbCat':'الأشعة',
    'post.title':'التصوير المقطعي يُصدر إشعاعًا أكثر بـ500 مرة!',
    'post.lead':'في بريطانيا، مُنع الأشخاص الأصحاء من إجراء تصوير مقطعي للجسم. ووفقًا لوزارة الصحة، فإن الإشعاع الذي يتعرض له الجسم أثناء التصوير المقطعي مرتفع كما هو لدى الناجين من القنبلة الذرية في هيروشيما.',
    'post.intro':'وقّعت وزارة الصحة البريطانية مساء أمس قرارًا بالغ الأهمية، وفرضت حظرًا على إجراء الأشخاص الأصحاء تصويرًا مقطعيًا للجسم. وعُلِّل اللجوء إلى هذا الحظر بأن نسبة الإشعاع المنبعث أثناء التصوير المقطعي والنافذ إلى الجسم مرتفعة جدًا. وكان التصوير المقطعي يُوصى به كثيرًا من قِبل خبراء الصحة في السنوات الماضية لأنه يتيح الكشف المبكر عن أمراض مثل هشاشة العظام وأمراض القلب وانسداد الأوعية والسكري.',
    'post.s1.h':'تصوير مقطعي واحد يعادل 442 صورة أشعة','post.s1.p1':'ذُكر في التقرير المنشور أن مستوى الإشعاع المتراكم في أجساد من يُكثرون التصوير المقطعي يماثل مستوى الناجين من القنبلتين الذريتين اللتين أُلقيتا على هيروشيما وناغازاكي في الحرب العالمية الثانية.','post.s1.p2':'بينما تُرسل صورة الأشعة العادية شعاعًا واحدًا لتصوير الجسم، يُرسَل في التصوير المقطعي عدة أشعة متتالية للحصول على صورة أكثر تفصيلًا. وفي دراسة أجرتها أواخر 2009 الأستاذة ريبيكا سميث-بيندمان من جامعة كاليفورنيا على 1119 شخصًا، تبيّن أن تصويرًا مقطعيًا واحدًا يُصدر إشعاعًا يعادل 442 صورة أشعة للصدر و74 صورة ماموغرام (أشعة الثدي).',
    'post.s2.h':'ما هو التصوير المقطعي المحوسب (CT)؟','post.s2.p1':'التصوير المقطعي المحوسب هو طريقة تشخيص شعاعية تهدف إلى تكوين صورة مقطعية للمنطقة المفحوصة من الجسم باستخدام الأشعة السينية. أثناء الفحص يستلقي المريض دون حركة على طاولة جهاز التصوير المقطعي. وتُدخَل الطاولة يدويًا أو بجهاز التحكم عن بُعد إلى فتحة الجهاز المسماة «الجانتري».','post.s2.p2':'الجهاز متصل بحاسوب. وبينما يقوم مصدر الأشعة السينية بحركة دورانية بزاوية 360 درجة حول المريض المفحوص، يُرصَد الجزء من حزمة الأشعة الذي يعبر الجسم بواسطة كواشف مصفوفة على طول «الجانتري»، وتُعالَج البيانات الناتجة بواسطة حاسوب.',
    'post.s3.h':'الرنين المغناطيسي لا آثار جانبية له!','post.s3.p1':'رغم هذا الخطر في التصوير المقطعي، توصّل الخبراء إلى إجماع على أن الرنين المغناطيسي لا آثار جانبية له. إذ تُستخدَم أثناء فحوص الرنين موجات راديوية فقط؛ وهي غير ضارة بصحة الإنسان.','post.s3.p2':'هو تصوير مقطعي لأي منطقة من الجسم. ويتكوّن جهاز الرنين المغناطيسي من مغناطيس عملاق. أثناء الفحص يُمدَّد المريض على طاولة الجهاز وتُدفَع الطاولة إلى النفق الموجود داخل المغناطيس العملاق. ويجب أثناء الفحص أن تبقى بلا حراك تمامًا.',
    'post.by':'كتبه:','post.role':'مشرف','post.related':'مقالات ذات صلة',
    'post.r1.cat':'صحة الأسنان','post.r1.t':'لماذا تؤلم الأسنان في الطقس البارد؟','post.r1.e':'بحثنا في العلاقة بين حساسية الأسنان والطقس البارد.',
    'post.r2.cat':'العلاج','post.r2.t':'ما مدى صحة العلاجات المستخدمة؟','post.r2.e':'تقييم من منظور الطب القائم على الأدلة.',
    'post.r3.cat':'السياحة الصحية','post.r3.t':'الضوء الأخضر لتأشيرة العلاج','post.r3.e':'إطار امتثال جديد لمسارات العلاج العابرة للحدود.'
  };
  I.nl = {
    'post.crumbCat':'Radiologie',
    'post.title':'CT-scans geven 500 keer meer straling af!',
    'post.lead':'In het Verenigd Koninkrijk zijn CT-scans van het lichaam voor gezonde mensen verboden. Volgens het ministerie van Volksgezondheid is de straling waaraan het lichaam tijdens een CT-scan wordt blootgesteld even hoog als die van de overlevenden van de atoombom in Hiroshima.',
    'post.intro':'De vorige avond nam het Britse ministerie van Volksgezondheid een zeer ingrijpend besluit en verbood het CT-scans van het lichaam voor gezonde mensen. Als reden voor dit verbod werd aangevoerd dat het stralingsniveau dat tijdens een CT-scan wordt afgegeven en in het lichaam doordringt, zeer hoog is. In voorgaande jaren werden CT-scans vaak door gezondheidsexperts aanbevolen omdat ze ziekten zoals osteoporose, hartaandoeningen, vaatafsluitingen en diabetes vroegtijdig konden opsporen.',
    'post.s1.h':'1 CT-scan staat gelijk aan 442 röntgenfoto’s','post.s1.p1':'In het gepubliceerde rapport werd vermeld dat het opgebouwde stralingsniveau in het lichaam van mensen die vaak CT-scans ondergaan, op hetzelfde niveau ligt als dat van de overlevenden van de atoombommen die in de Tweede Wereldoorlog op Hiroshima en Nagasaki werden gegooid.','post.s1.p2':'Terwijl een gewone röntgenfoto één straal uitzendt om het lichaam in beeld te brengen, worden bij een CT-scan vele stralen na elkaar uitgezonden om een gedetailleerder beeld te verkrijgen. In een onderzoek dat eind 2009 door prof. Rebecca Smith-Bindman van de Universiteit van Californië onder 1.119 mensen werd uitgevoerd, bleek dat één CT-scan evenveel straling afgeeft als 442 borströntgenfoto’s en 74 mammografieën (borströntgen).',
    'post.s2.h':'Wat is computertomografie (CT)?','post.s2.p1':'Computertomografie is een radiologische diagnosemethode die met behulp van röntgenstraling een dwarsdoorsnedebeeld van het onderzochte lichaamsgebied maakt. Tijdens het onderzoek ligt de patiënt zonder te bewegen op de tafel van het CT-apparaat. De tafel wordt handmatig of met een afstandsbediening in de opening van het apparaat geschoven die de “gantry” wordt genoemd.','post.s2.p2':'Het apparaat is verbonden met een computer. Terwijl de röntgenbron een draaiende beweging van 360 graden rond de onderzochte patiënt maakt, wordt het deel van de röntgenbundel dat door het lichaam gaat, gedetecteerd door detectoren die langs de “gantry” zijn opgesteld, en worden de verkregen gegevens door een computer verwerkt.',
    'post.s3.h':'MRI heeft geen bijwerkingen!','post.s3.p1':'Ondanks dit risico bij CT bereikten de experts consensus dat MRI geen enkele bijwerking heeft. Bij MRI-scans worden alleen radiogolven gebruikt; en die zijn onschadelijk voor de menselijke gezondheid.','post.s3.p2':'Het is de dwarsdoorsnede-beeldvorming van een willekeurig lichaamsgebied. Het MRI-apparaat bestaat uit een reusachtige magneet. Tijdens het onderzoek wordt de patiënt op de tafel van het apparaat gelegd en wordt de tafel in de tunnel binnen de reusachtige magneet geschoven. Tijdens het onderzoek moet u absoluut stil blijven liggen.',
    'post.by':'Geschreven door:','post.role':'Moderator','post.related':'Gerelateerde artikelen',
    'post.r1.cat':'Mondgezondheid','post.r1.t':'Waarom doen tanden pijn bij koud weer?','post.r1.e':'Wij onderzochten het verband tussen gevoelige tanden en koud weer.',
    'post.r2.cat':'Behandeling','post.r2.t':'Hoe juist zijn de gebruikte behandelingen?','post.r2.e':'Een beoordeling vanuit het perspectief van evidence-based geneeskunde.',
    'post.r3.cat':'Medisch toerisme','post.r3.t':'Groen licht voor het gezondheidsvisum','post.r3.e':'Een nieuw nalevingskader voor grensoverschrijdende behandeltrajecten.'
  };
})(window.HP_I18N);
