/* ============================================================
   Healthperia — i18n-detail.js  (treatment DETAIL page chrome)
   MERGE-style (loaded after i18n-treatment.js, before main.js) so
   it adds td.* without clobbering ti.* on window.HP_I18N.
   Doctor-entered content (process, bio, descriptions) stays as-is.
   ============================================================ */
window.HP_I18N = window.HP_I18N || {};
(function (I) {
  'use strict';
  function add(lang, obj) { I[lang] = Object.assign(I[lang] || {}, obj); }

  add('tr', { 'td.crumb':'Detay','td.notFound':'İlan bulunamadı.','td.backToIndex':'Tedavi İndeksine dön','td.contact':'İletişime Geç','td.fav':'Favorilere Ekle','td.favOn':'Favorilerde','td.share':'Paylaş','td.openMaps':'Konumu Haritada Göster','td.photos':'Fotoğraflar','td.noPhotos':'Doktor henüz fotoğraf eklememiş.','td.s.process':'Tedavi Süreci','td.s.doctor':'Doktor Bilgisi','td.s.place':'Tedavi Yeri','td.s.transport':'Ulaşım Bilgisi','td.s.hotel':'Otel Bilgisi','td.s.adv':'Ek Avantajlar','td.s.price':'Fiyat Bilgisi','td.price.range':'Fiyat Aralığı','td.price.installment':'Taksit İmkânı','td.price.yes':'Var','td.price.no':'Yok','td.shareTitle':'Bu ilanı paylaş','td.copy':'Kopyala','td.copied':'Kopyalandı ✓' });
  add('en', { 'td.crumb':'Details','td.notFound':'Listing not found.','td.backToIndex':'Back to Treatment Index','td.contact':'Contact','td.fav':'Add to Favorites','td.favOn':'In Favorites','td.share':'Share','td.openMaps':'Show Location on Map','td.photos':'Photos','td.noPhotos':"The doctor hasn't added photos yet.",'td.s.process':'Treatment Process','td.s.doctor':'Doctor Info','td.s.place':'Treatment Location','td.s.transport':'Transport Info','td.s.hotel':'Hotel Info','td.s.adv':'Extra Advantages','td.s.price':'Price Info','td.price.range':'Price Range','td.price.installment':'Installment Option','td.price.yes':'Available','td.price.no':'Not available','td.shareTitle':'Share this listing','td.copy':'Copy','td.copied':'Copied ✓' });
  add('de', { 'td.crumb':'Details','td.notFound':'Anzeige nicht gefunden.','td.backToIndex':'Zurück zum Behandlungsindex','td.contact':'Kontakt aufnehmen','td.fav':'Zu Favoriten','td.favOn':'In Favoriten','td.share':'Teilen','td.openMaps':'Standort auf Karte anzeigen','td.photos':'Fotos','td.noPhotos':'Der Arzt hat noch keine Fotos hinzugefügt.','td.s.process':'Behandlungsablauf','td.s.doctor':'Arztinformationen','td.s.place':'Behandlungsort','td.s.transport':'Transportinfo','td.s.hotel':'Hotelinfo','td.s.adv':'Zusätzliche Vorteile','td.s.price':'Preisinformationen','td.price.range':'Preisspanne','td.price.installment':'Ratenzahlung','td.price.yes':'Verfügbar','td.price.no':'Nicht verfügbar','td.shareTitle':'Diese Anzeige teilen','td.copy':'Kopieren','td.copied':'Kopiert ✓' });
  add('ru', { 'td.crumb':'Детали','td.notFound':'Объявление не найдено.','td.backToIndex':'Назад к индексу лечения','td.contact':'Связаться','td.fav':'В избранное','td.favOn':'В избранном','td.share':'Поделиться','td.openMaps':'Показать местоположение на карте','td.photos':'Фотографии','td.noPhotos':'Врач ещё не добавил фотографии.','td.s.process':'Процесс лечения','td.s.doctor':'О враче','td.s.place':'Место лечения','td.s.transport':'Транспорт','td.s.hotel':'Отель','td.s.adv':'Доп. преимущества','td.s.price':'Цена','td.price.range':'Диапазон цен','td.price.installment':'Рассрочка','td.price.yes':'Есть','td.price.no':'Нет','td.shareTitle':'Поделиться объявлением','td.copy':'Копировать','td.copied':'Скопировано ✓' });
  add('fr', { 'td.crumb':'Détails','td.notFound':'Annonce introuvable.','td.backToIndex':"Retour à l'index des traitements",'td.contact':'Contacter','td.fav':'Ajouter aux favoris','td.favOn':'Dans les favoris','td.share':'Partager','td.openMaps':"Afficher l'emplacement sur la carte",'td.photos':'Photos','td.noPhotos':"Le médecin n'a pas encore ajouté de photos.",'td.s.process':'Processus de traitement','td.s.doctor':'Informations du médecin','td.s.place':'Lieu de traitement','td.s.transport':'Informations de transport','td.s.hotel':"Informations sur l'hôtel",'td.s.adv':'Avantages supplémentaires','td.s.price':'Informations sur le prix','td.price.range':'Fourchette de prix','td.price.installment':'Paiement échelonné','td.price.yes':'Disponible','td.price.no':'Non disponible','td.shareTitle':'Partager cette annonce','td.copy':'Copier','td.copied':'Copié ✓' });
  add('es', { 'td.crumb':'Detalles','td.notFound':'Anuncio no encontrado.','td.backToIndex':'Volver al índice de tratamientos','td.contact':'Contactar','td.fav':'Añadir a favoritos','td.favOn':'En favoritos','td.share':'Compartir','td.openMaps':'Mostrar ubicación en el mapa','td.photos':'Fotos','td.noPhotos':'El médico aún no ha añadido fotos.','td.s.process':'Proceso de tratamiento','td.s.doctor':'Información del médico','td.s.place':'Lugar del tratamiento','td.s.transport':'Información de transporte','td.s.hotel':'Información del hotel','td.s.adv':'Ventajas adicionales','td.s.price':'Información de precio','td.price.range':'Rango de precios','td.price.installment':'Opción de cuotas','td.price.yes':'Disponible','td.price.no':'No disponible','td.shareTitle':'Compartir este anuncio','td.copy':'Copiar','td.copied':'Copiado ✓' });
  add('pt', { 'td.crumb':'Detalhes','td.notFound':'Anúncio não encontrado.','td.backToIndex':'Voltar ao índice de tratamentos','td.contact':'Contatar','td.fav':'Adicionar aos favoritos','td.favOn':'Nos favoritos','td.share':'Compartilhar','td.openMaps':'Mostrar localização no mapa','td.photos':'Fotos','td.noPhotos':'O médico ainda não adicionou fotos.','td.s.process':'Processo de tratamento','td.s.doctor':'Informações do médico','td.s.place':'Local do tratamento','td.s.transport':'Informações de transporte','td.s.hotel':'Informações do hotel','td.s.adv':'Vantagens adicionais','td.s.price':'Informações de preço','td.price.range':'Faixa de preço','td.price.installment':'Opção de parcelamento','td.price.yes':'Disponível','td.price.no':'Indisponível','td.shareTitle':'Compartilhar este anúncio','td.copy':'Copiar','td.copied':'Copiado ✓' });
  add('ar', { 'td.crumb':'التفاصيل','td.notFound':'لم يتم العثور على الإعلان.','td.backToIndex':'العودة إلى فهرس العلاجات','td.contact':'تواصل','td.fav':'أضف إلى المفضلة','td.favOn':'في المفضلة','td.share':'مشاركة','td.openMaps':'إظهار الموقع على الخريطة','td.photos':'الصور','td.noPhotos':'لم يضف الطبيب صورًا بعد.','td.s.process':'مسار العلاج','td.s.doctor':'معلومات الطبيب','td.s.place':'مكان العلاج','td.s.transport':'معلومات النقل','td.s.hotel':'معلومات الفندق','td.s.adv':'مزايا إضافية','td.s.price':'معلومات السعر','td.price.range':'نطاق السعر','td.price.installment':'إمكانية التقسيط','td.price.yes':'متوفر','td.price.no':'غير متوفر','td.shareTitle':'شارك هذا الإعلان','td.copy':'نسخ','td.copied':'تم النسخ ✓' });
  add('nl', { 'td.crumb':'Details','td.notFound':'Advertentie niet gevonden.','td.backToIndex':'Terug naar behandelingsindex','td.contact':'Contact opnemen','td.fav':'Aan favorieten toevoegen','td.favOn':'In favorieten','td.share':'Delen','td.openMaps':'Locatie op kaart tonen','td.photos':"Foto's",'td.noPhotos':"De arts heeft nog geen foto's toegevoegd.",'td.s.process':'Behandelproces','td.s.doctor':'Artsinformatie','td.s.place':'Behandellocatie','td.s.transport':'Vervoersinformatie','td.s.hotel':'Hotelinformatie','td.s.adv':'Extra voordelen','td.s.price':'Prijsinformatie','td.price.range':'Prijsklasse','td.price.installment':'Termijnbetaling','td.price.yes':'Beschikbaar','td.price.no':'Niet beschikbaar','td.shareTitle':'Deel deze advertentie','td.copy':'Kopiëren','td.copied':'Gekopieerd ✓' });
})(window.HP_I18N);
